// <auto-generated />
using System;
using CONTROL_TICKET_TAREA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CONTROL_TICKET_TAREA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CONTROL_TICKET_TAREA.Models.TbControlTicketTarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .HasColumnType("int")
                        .HasColumnName("ID_TAREA");

                    b.Property<string>("CodTicket")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("COD_TICKET");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CONTACTO");

                    b.Property<string>("CorrelConcatExterno")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CORREL_CONCAT_EXTERNO");

                    b.Property<string>("CorrelEmp")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CORREL_EMP");

                    b.Property<string>("CorrelSup")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CORREL_SUP");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<DateTime?>("FecAct")
                        .HasColumnType("datetime")
                        .HasColumnName("FEC_ACT");

                    b.Property<DateTime?>("FecReg")
                        .HasColumnType("datetime")
                        .HasColumnName("FEC_REG");

                    b.Property<DateTime>("FechaTicketTarea")
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_TICKET_TAREA");

                    b.Property<int?>("Flag")
                        .HasColumnType("int")
                        .HasColumnName("FLAG");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO");

                    b.Property<int>("IdGe")
                        .HasColumnType("int")
                        .HasColumnName("ID_GE");

                    b.Property<int>("IdItemCenter")
                        .HasColumnType("int")
                        .HasColumnName("ID_ITEM_CENTER");

                    b.Property<string>("IdItemCenterDesc")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ID_ITEM_CENTER_DESC");

                    b.Property<int>("IdMedia")
                        .HasColumnType("int")
                        .HasColumnName("ID_MEDIA");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRIORIDAD");

                    b.Property<int>("IdReceptor")
                        .HasColumnType("int")
                        .HasColumnName("ID_RECEPTOR");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("ID_TIPO");

                    b.Property<string>("NSerie")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("N_SERIE");

                    b.Property<int?>("UsuAct")
                        .HasColumnType("int")
                        .HasColumnName("USU_ACT");

                    b.Property<int?>("UsuReg")
                        .HasColumnType("int")
                        .HasColumnName("USU_REG");

                    b.HasKey("IdTarea")
                        .HasName("PK__TB_CONTR__3484F0F970E5E80C");

                    b.ToTable("TB_CONTROL_TICKET_TAREA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
